services:
  postgres:
    image: postgres:16-alpine
    container_name: wellpulse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wellpulse
      POSTGRES_PASSWORD: wellpulse
      POSTGRES_DB: wellpulse_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wellpulse']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wellpulse-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: wellpulse-mailpit
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP
      - '3003:8025' # Web UI
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - mailpit_data:/data

  minio:
    image: minio/minio:latest
    container_name: wellpulse-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: wellpulse
      MINIO_ROOT_PASSWORD: wellpulse123
    ports:
      - '9000:9000' # API
      - '9001:9001' # Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: wellpulse-otel
    restart: unless-stopped
    command: ['--config=/etc/otel-collector-config.yml']
    ports:
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
      - '8888:8888' # Prometheus metrics
      - '13133:13133' # Health check
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml

volumes:
  postgres_data:
  redis_data:
  mailpit_data:
  minio_data:
