name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [master, main]

jobs:
  deploy-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    if: false # Disabled - requires RAILWAY_TOKEN secret
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Railway CLI
        run: pnpm add -g @railway/cli

      - name: Deploy API to Railway PR environment
        run: railway up --service api --environment pr-${{ github.event.pull_request.number }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Web to Railway PR environment
        run: railway up --service web --environment pr-${{ github.event.pull_request.number }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Get Railway URLs
        id: railway-urls
        run: |
          API_URL=$(railway status --service api --environment pr-${{ github.event.pull_request.number }} --json | jq -r '.url')
          WEB_URL=$(railway status --service web --environment pr-${{ github.event.pull_request.number }} --json | jq -r '.url')
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "web_url=$WEB_URL" >> $GITHUB_OUTPUT
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Comment PR with preview URLs
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('🚀 Preview Deployment')
            );

            const body = `## 🚀 Preview Deployment

            Your preview environment is ready!

            | Service | URL |
            | ------- | --- |
            | 🌐 **Web App** | ${{ steps.railway-urls.outputs.web_url }} |
            | 🔌 **API** | ${{ steps.railway-urls.outputs.api_url }} |
            | 📚 **API Docs** | ${{ steps.railway-urls.outputs.api_url }}/api/docs |
            | ❤️ **Health Check** | ${{ steps.railway-urls.outputs.api_url }}/health |

            **Environment:** \`pr-${{ github.event.pull_request.number }}\`
            **Commit:** \`${{ github.event.pull_request.head.sha }}\`

            ---
            *This preview will be automatically deleted when the PR is closed.*`;

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body
              });
            }

  cleanup-preview:
    name: Cleanup PR Preview
    runs-on: ubuntu-latest
    if: false # Disabled - requires RAILWAY_TOKEN secret
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Railway CLI
        run: pnpm add -g @railway/cli

      - name: Delete Railway PR environment
        run: railway environment delete pr-${{ github.event.pull_request.number }} --yes
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        continue-on-error: true

      - name: Comment PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🧹 Preview environment has been deleted.'
            });
